version: '3.3'

services: 
  db : 
    image : mysql:5.7
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE : ubuntudb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      DATABASE_HOST: db
  node-app : 
    build : ../backend
    volumes: 
      - ../backend/app
    environment: 
      MYSQL_DATABASE : ubuntudb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      DATABASE_HOST: db
      MYSQL_PORT : 3306
    ports :
      - "8081:8081"
    depends_on: 
      - db
    restart: on-failure
    command: sh -c "npm i && npm run serve:dev"